spring:
  profiles:
    active: local
  datasource:
    # 1. El puerto es 5432 (mapeado en docker)
    # 2. El nombre de la base de datos es 'clasified_files' (según tu POSTGRES_DB)
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clasified_files}
    
    # 3. El usuario es 'red_panda_us' (según tu POSTGRES_USER)
    username: ${DB_USER:red_panda_us}
    
    # 4. La contraseña es 'red_panda_passw' (según tu POSTGRES_PASSWORD)
    password: ${DB_PASSWORD:red_panda_passw}
    
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    user:
      password: disabled

google:
  client-id: ${GOOGLE_CLIENT_ID:271645130319-2raursujnehhvpjcj6g015kpn9rqfnbs.apps.googleusercontent.com}
  
jwt:
  secret: ${JWT_SECRET:esta_es_una_clave_secreta_muy_larga_para_el_mvp_de_mañana_2024}
  expiration-ms: 86400000

server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: .*

game:
  profanity-blacklist: tonto,tontito,caraculo,botijo,mierda,puto,puta,cabron,gilipollas
  tema-basico-id: 1
  ranking-global-size: 10
  ranking-amigos-size: 100
  timer-pool-size: 4
  penalizacion-abandono: 10
  balas-ganador: 20
  balas-derrota: 10
  timeout-reconexion: 60